# Streamlit Cloud Secrets
# These will be automatically picked up by Streamlit Cloud

[environment]
ENVIRONMENT = "production"
IS_STREAMLIT_CLOUD = "true"
FORCE_PRODUCTION = "true"

[supabase]
url = "https://jjxmfidggofuaxcdtkrd.supabase.co"
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqeG1maWRnZ29mdWF4Y2R0a3JkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODEyMTE0NCwiZXhwIjoyMDczNjk3MTQ0fQ.MaeZ2hEJXoC_Fz2BlO42QlDfg7s9TRNhoHGuzMERWEE"