[theme]
primaryColor = "#1351b4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[theme.sidebar]
backgroundColor = "#f8f9fa"
widgetBackgroundColor = "#ffffff"

[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false

[logger]
level = "info"

[client]
toolbarMode = "auto"